// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90Fb5G8Y20rqy7c-dygp0H5kxECU7UDQ',
    appId: '1:800047929275:web:a2444c0773f5208bc8569e',
    messagingSenderId: '800047929275',
    projectId: 'yene-taxi-41de2',
    authDomain: 'yene-taxi-41de2.firebaseapp.com',
    storageBucket: 'yene-taxi-41de2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzOJHfnwAvX3Xly2Vso8ur6F_S1lHr-s',
    appId: '1:800047929275:android:14982e2ecf2ef3e6c8569e',
    messagingSenderId: '800047929275',
    projectId: 'yene-taxi-41de2',
    storageBucket: 'yene-taxi-41de2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmzoy-a9bKARzmNwwpNTis8UXYQDc_Rc',
    appId: '1:800047929275:ios:23808033587ac80cc8569e',
    messagingSenderId: '800047929275',
    projectId: 'yene-taxi-41de2',
    storageBucket: 'yene-taxi-41de2.firebasestorage.app',
    iosClientId:
        '800047929275-ha1hhbdapvqom0ubhqc2gmiskhnputvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeneTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlmzoy-a9bKARzmNwwpNTis8UXYQDc_Rc',
    appId: '1:800047929275:ios:23808033587ac80cc8569e',
    messagingSenderId: '800047929275',
    projectId: 'yene-taxi-41de2',
    storageBucket: 'yene-taxi-41de2.firebasestorage.app',
    iosClientId:
        '800047929275-ha1hhbdapvqom0ubhqc2gmiskhnputvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeneTaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD90Fb5G8Y20rqy7c-dygp0H5kxECU7UDQ',
    appId: '1:800047929275:web:a2444c0773f5208bc8569e',
    messagingSenderId: '800047929275',
    projectId: 'yene-taxi-41de2',
    authDomain: 'yene-taxi-41de2.firebaseapp.com',
    storageBucket: 'yene-taxi-41de2.firebasestorage.app',
  );
}
